version: '3.8'

services.
wings
image: ghcr.io/pterodactyl/wings v1.6.1
7
restart: always
networks
-wings0
ports:
11
443:443"
12
tty: true
13
environment:
15
TZ UTC
WINGS LAD: 988
WINGS GID: 988
WINGS USERNAME: pterodactyl
volumes:
"/var/run/docker.sock/var/run/docker.sock"
"/var/lib/docker/containers//var/lib/docker/containers
/etc/pterodactyl/:/etc/pterodactyl
"/var/lib/pterodactyl/:/var/lib/pterodactyl/
-"/var/log/pterodactyl/:/var/log/pterodactyl/" "/tmp/pterodactyl/:/tmp/pterodactyl/
/etc/ssl/certs/etc/ssl/certscro
#you may need /srv/daemon-data if you are upgradin
from an old daemon
#/srv/daemon-data//srv/daemon-data/"
#Required for ssl if you use let's encrypt. uncommem
to use
#"/etc/letsencrypt/:/etc/letsencrypt/
networks:
wings0
narrie: wingso
driver: bridge
pam
config
subnet: 172.21.0.0/16
driver opts
com.docker.network.bridge.name: wings
